package nextstep.signup.signup

enum class SignUpInputValidationType {
    USERNAME_LENGTH_ERROR,
    USERNAME_FORMAT_ERROR,
    EMAIL_FORMAT_ERROR,
    PASSWORD_LENGTH_ERROR,
    PASSWORD_FORMAT_ERROR,
    PASSWORD_MISMATCH_ERROR,
    VALID
}
